version: '3.8'
services:
 backend:
 build:
 context: .
 dockerfile: backend/Dockerfile
 ports:
 - "8000:8000"
 volumes:
 - ./backend:/app
 env_file:
 - ./backend/.env
 depends_on:
 - db
 frontend:
 build:
 context: .
 dockerfile: frontend/Dockerfile
 ports:
 - "3000:3000"
 volumes:
 - ./frontend:/app
 stdin_open: true
 tty: true
 db:
 image: mysql:8.0
 restart: always
 environment:
 MYSQL_ROOT_PASSWORD: root1234
 MYSQL_DATABASE: imagegen
 ports:
 - "3306:3306"
 volumes:
 - db_data:/var/lib/mysql
volumes:
 db_data:
