# Generated by Django 5.2.1 on 2025-06-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='미분류', max_length=50),
            preserve_default=False,
        ),
    ]
