# Generated by Django 5.2.2 on 2025-06-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.ImageField(blank=True, null=True, upload_to='products/details/'),
        ),
    ]
